# Generated by Django 4.0.1 on 2022-01-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_issues_comment_issue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('PARTICIPANT', 'Participant')], default='PART', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='Unique User/Project'),
        ),
    ]
